const ADMIN_PASSWORD="1234";
const DEFAULT_SERVICES=[{title:"상가철거",desc:"상가, 매장, 카페, 식당 등 내부 철거",detailDesc:"상가철거 상세 설명",mainImage:"",detailImages:[]},{title:"사무실철거",desc:"사무실 집기, 칸막이, 천장, 바닥 철거",detailDesc:"사무실철거 상세 설명",mainImage:"",detailImages:[]},{title:"원상복구",desc:"임대차 종료 전 필요한 원상복구",detailDesc:"원상복구 상세 설명",mainImage:"",detailImages:[]},{title:"인테리어",desc:"철거 후 인테리어 마감",detailDesc:"인테리어 상세 설명",mainImage:"",detailImages:[]},{title:"폐기물처리",desc:"현장 폐기물 반출과 정리",detailDesc:"폐기물처리 상세 설명",mainImage:"",detailImages:[]},{title:"현장정리",desc:"공사 후 현장 정리",detailDesc:"현장정리 상세 설명",mainImage:"",detailImages:[]}];let editIndex=null;
function getData(k,f){return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}function setData(k,v){localStorage.setItem(k,JSON.stringify(v))}function fileToData(file){return new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.readAsDataURL(file)})}
function login(){if(password.value===ADMIN_PASSWORD){localStorage.setItem("renovaAdmin","1");loginBox.style.display="none";dash.style.display="block";loadAll()}else alert("비밀번호가 다릅니다.")}
function logout(){localStorage.removeItem("renovaAdmin");location.reload()}function loadAll(){loadAbout();loadServices();loadSettings();renderCases()}
async function saveHero(){if(heroImage.files[0]){setData("renovaHero",{image:await fileToData(heroImage.files[0])});alert("배너 저장 완료")}}
function loadAbout(){const a=getData("renovaAbout",{images:[]});aboutPreview.innerHTML=(a.images||[]).map((img,i)=>`<div class="imgBox"><img src="${img}" onclick="openAdminImage('${img}')"><button onclick="removeAboutImg(${i})">X</button></div>`).join("")}
async function saveAbout(){const imgs=await Promise.all([...aboutImgs.files].slice(0,3).map(fileToData));setData("renovaAbout",{images:imgs});aboutImgs.value="";loadAbout();alert("회사소개 이미지 저장 완료")}
function removeAboutImg(i){const a=getData("renovaAbout",{images:[]});a.images.splice(i,1);setData("renovaAbout",a);loadAbout()}function clearAbout(){setData("renovaAbout",{images:[]});loadAbout()}
function loadServices(){const s=getData("renovaServices",DEFAULT_SERVICES);serviceSimpleList.innerHTML=s.map((x,i)=>`<div class="serviceRow"><div><b>${x.title}</b><br><small>${x.desc}</small></div><button onclick="openServiceEditor(${i})">이미지 교체</button></div>`).join("")}
function openServiceEditor(i){editIndex=i;const s=getData("renovaServices",DEFAULT_SERVICES)[i];editServiceTitle.textContent=s.title+" 이미지 교체";editTitle.value=s.title;editDesc.value=s.desc;editDetailDesc.value=s.detailDesc||"";editMainPreview.innerHTML=s.mainImage?`<img src="${s.mainImage}" onclick="openAdminImage('${s.mainImage}')">`:"";renderDetailPreview(s.detailImages||[]);serviceEditor.classList.add("show")}
function closeServiceEditor(){serviceEditor.classList.remove("show")}function renderDetailPreview(imgs){editDetailPreview.innerHTML=(imgs||[]).map((img,i)=>`<div class="imgBox"><img src="${img}" onclick="openAdminImage('${img}')"><button onclick="removeDetailImg(${i})">X</button></div>`).join("")}
function removeDetailImg(i){const s=getData("renovaServices",DEFAULT_SERVICES);s[editIndex].detailImages.splice(i,1);setData("renovaServices",s);renderDetailPreview(s[editIndex].detailImages)}
async function saveServiceEditor(){const s=getData("renovaServices",DEFAULT_SERVICES);const item=s[editIndex];item.title=editTitle.value;item.desc=editDesc.value;item.detailDesc=editDetailDesc.value;if(editMainImage.files[0])item.mainImage=await fileToData(editMainImage.files[0]);if(editDetailImages.files.length){const imgs=await Promise.all([...editDetailImages.files].map(fileToData));item.detailImages=[...(item.detailImages||[]),...imgs]}setData("renovaServices",s);editMainImage.value="";editDetailImages.value="";closeServiceEditor();loadServices();alert("서비스 저장 완료")}
function saveSettings(){setData("renovaSettings",{phone1:phone1Input.value,phone2:phone2Input.value,blog:blogInput.value,kakao:kakaoInput.value});alert("저장 완료")}function loadSettings(){const s=getData("renovaSettings",{phone1:"010-8476-7456",phone2:"010-9169-7557",blog:"",kakao:""});phone1Input.value=s.phone1;phone2Input.value=s.phone2;blogInput.value=s.blog;kakaoInput.value=s.kakao}
async function saveCase(){const title=caseTitle.value.trim(),desc=caseDesc.value.trim();if(!title){alert("제목을 입력하세요");return}const imgs=await Promise.all([...caseImages.files].slice(0,10).map(fileToData));const cases=getData("renovaCases",[]);cases.unshift({id:Date.now(),title,desc,images:imgs});setData("renovaCases",cases);caseTitle.value="";caseDesc.value="";caseImages.value="";renderCases();alert("시공사례 저장 완료")}
function renderCases(){const cases=getData("renovaCases",[]);caseList.innerHTML=cases.map(c=>`<div class="card"><h3>${c.title}</h3><p>${c.desc||""}</p><div class="previewGrid">${(c.images||[]).map(img=>`<img src="${img}" onclick="openAdminImage('${img}')">`).join("")}</div><button class="danger" onclick="deleteCase(${c.id})">삭제</button></div>`).join("")}function deleteCase(id){setData("renovaCases",getData("renovaCases",[]).filter(x=>x.id!==id));renderCases()}
function openAdminImage(src){let b=document.querySelector(".lightbox");if(!b){b=document.createElement("div");b.className="lightbox";b.innerHTML="<img>";b.onclick=()=>b.classList.remove("show");document.body.appendChild(b)}b.querySelector("img").src=src;b.classList.add("show")}
document.addEventListener("DOMContentLoaded",()=>{if(localStorage.getItem("renovaAdmin")==="1"){loginBox.style.display="none";dash.style.display="block";loadAll()}})