const DEFAULT_SERVICES=[{title:"상가철거",desc:"상가, 매장, 카페, 식당 등 내부 철거",detailDesc:"상가철거 상세 설명",mainImage:"",detailImages:[]},{title:"사무실철거",desc:"사무실 집기, 칸막이, 천장, 바닥 철거",detailDesc:"사무실철거 상세 설명",mainImage:"",detailImages:[]},{title:"원상복구",desc:"임대차 종료 전 필요한 원상복구",detailDesc:"원상복구 상세 설명",mainImage:"",detailImages:[]},{title:"인테리어",desc:"철거 후 인테리어 마감",detailDesc:"인테리어 상세 설명",mainImage:"",detailImages:[]},{title:"폐기물처리",desc:"현장 폐기물 반출과 정리",detailDesc:"폐기물처리 상세 설명",mainImage:"",detailImages:[]},{title:"현장정리",desc:"공사 후 현장 정리",detailDesc:"현장정리 상세 설명",mainImage:"",detailImages:[]}];let editIndex=null;const ADMIN_PASSWORD="1234";
function getData(k,f){return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}function setData(k,v){localStorage.setItem(k,JSON.stringify(v))}function fileToData(file){return new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.readAsDataURL(file)})}function onlyNumber(v){return (v||"").replace(/[^0-9]/g,"")}
const menuBtn=document.getElementById("menuBtn"),nav=document.getElementById("nav");if(menuBtn)menuBtn.onclick=()=>nav.classList.toggle("open");
function applySettings(){const s=getData("renovaSettings",{phone1:"010-8476-7456",phone2:"010-9169-7557",blog:"#",kakao:"#"});phone1.textContent=s.phone1;phone1.href="tel:"+onlyNumber(s.phone1);phone2.textContent=s.phone2;phone2.href="tel:"+onlyNumber(s.phone2);mainPhone.href="tel:"+onlyNumber(s.phone1);blogLink.href=s.blog||"#";kakaoLink.href=s.kakao||"#"}
function renderHero(){const h=getData("renovaHero",{image:""});if(h.image)heroBg.style.backgroundImage=`url(${h.image})`}
function renderAbout(){const a=getData("renovaAbout",{images:[]});aboutImages.innerHTML=(a.images||[]).slice(0,3).map(src=>`<img src="${src}" onclick="openImage('${src}')">`).join("")}
function renderServices(){const list=getData("renovaServices",DEFAULT_SERVICES);serviceGrid.innerHTML=list.map((s,i)=>`<article class="serviceCard">${s.mainImage?`<img src="${s.mainImage}" onclick="openService(${i})">`:`<div class="emptyImg">서비스 이미지</div>`}<h3>${s.title}</h3><p>${s.desc}</p><a class="detailBtn" href="javascript:void(0)" onclick="openService(${i})">상세보기</a></article>`).join("")}
function openService(i){const list=getData("renovaServices",DEFAULT_SERVICES),s=list[i];let m=document.querySelector(".modal");if(!m){m=document.createElement("div");m.className="modal";document.body.appendChild(m)}m.innerHTML=`<div class="modalBox"><button class="modalClose" onclick="document.querySelector('.modal').classList.remove('show')">닫기</button><h2>${s.title}</h2><p>${s.detailDesc||s.desc||""}</p><div class="detailImages">${(s.detailImages||[]).map(img=>`<img src="${img}" onclick="openImage('${img}')">`).join("")}</div></div>`;m.classList.add("show")}
function renderCases(){const cases=getData("renovaCases",[]);if(!cases.length){caseGallery.innerHTML='<article class="caseCard"><div class="emptyImg">시공사례 이미지</div><h3>시공사례 준비중</h3><p>관리자에서 등록하면 표시됩니다.</p></article>';return}caseGallery.innerHTML=cases.map(c=>`<article class="caseCard"><div class="caseImgs">${(c.images||[]).slice(0,10).map(img=>`<img src="${img}" onclick="openImage('${img}')">`).join("")}</div><h3>${c.title}</h3><p>${c.desc||""}</p></article>`).join("")}
function refreshSite(){applySettings();renderHero();renderAbout();renderServices();renderCases()}
function openImage(src){let m=document.querySelector(".modal");if(!m){m=document.createElement("div");m.className="modal";document.body.appendChild(m)}m.innerHTML=`<div class="modalBox"><button class="modalClose" onclick="document.querySelector('.modal').classList.remove('show')">닫기</button><img src="${src}" style="width:100%;max-height:80vh;object-fit:contain"></div>`;m.classList.add("show")}
function openAdminLogin(){adminPanel.classList.add("show");if(localStorage.getItem("renovaAdmin")==="1"){document.getElementById("adminLoginBox").style.display="none";document.getElementById("adminDash").style.display="block";loadAdmin()}}
function closeAdmin(){adminPanel.classList.remove("show")}
function doAdminLogin(){
  const pw=document.getElementById("adminPassword").value.trim();
  if(pw==="1234"){
    localStorage.setItem("renovaAdmin","1");
    document.getElementById("adminLoginBox").style.display="none";
    document.getElementById("adminDash").style.display="block";
    loadAdmin();
  }else{
    alert("비밀번호가 다릅니다.");
  }
}
function adminLogout(){localStorage.removeItem("renovaAdmin");document.getElementById("adminDash").style.display="none";document.getElementById("adminLoginBox").style.display="block"}
function loadAdmin(){loadAboutAdmin();loadServicesAdmin();loadSettingsAdmin();renderCasesAdmin()}
async function saveHero(){if(heroImage.files[0]){setData("renovaHero",{image:await fileToData(heroImage.files[0])});refreshSite();alert("배너 저장 완료")}}
function loadAboutAdmin(){const a=getData("renovaAbout",{images:[]});aboutPreview.innerHTML=(a.images||[]).map((img,i)=>`<div class="imgBox"><img src="${img}" onclick="openImage('${img}')"><button onclick="removeAboutImg(${i})">X</button></div>`).join("")}
async function saveAbout(){const imgs=await Promise.all([...aboutImgs.files].slice(0,3).map(fileToData));setData("renovaAbout",{images:imgs});aboutImgs.value="";loadAboutAdmin();refreshSite();alert("회사소개 이미지 저장 완료")}
function removeAboutImg(i){const a=getData("renovaAbout",{images:[]});a.images.splice(i,1);setData("renovaAbout",a);loadAboutAdmin();refreshSite()}function clearAbout(){setData("renovaAbout",{images:[]});loadAboutAdmin();refreshSite()}
function loadServicesAdmin(){const s=getData("renovaServices",DEFAULT_SERVICES);serviceSimpleList.innerHTML=s.map((x,i)=>`<div class="serviceRow"><div><b>${x.title}</b><br><small>${x.desc}</small></div><button onclick="openServiceEditor(${i})">이미지 교체</button></div>`).join("")}
function openServiceEditor(i){editIndex=i;const s=getData("renovaServices",DEFAULT_SERVICES)[i];editServiceTitle.textContent=s.title+" 이미지 교체";editTitle.value=s.title;editDesc.value=s.desc;editDetailDesc.value=s.detailDesc||"";editMainPreview.innerHTML=s.mainImage?`<img src="${s.mainImage}" onclick="openImage('${s.mainImage}')">`:"";renderDetailPreview(s.detailImages||[]);serviceEditor.classList.add("show")}
function closeServiceEditor(){serviceEditor.classList.remove("show")}function renderDetailPreview(imgs){editDetailPreview.innerHTML=(imgs||[]).map((img,i)=>`<div class="imgBox"><img src="${img}" onclick="openImage('${img}')"><button onclick="removeDetailImg(${i})">X</button></div>`).join("")}
function removeDetailImg(i){const s=getData("renovaServices",DEFAULT_SERVICES);s[editIndex].detailImages.splice(i,1);setData("renovaServices",s);renderDetailPreview(s[editIndex].detailImages);refreshSite()}
async function saveServiceEditor(){const s=getData("renovaServices",DEFAULT_SERVICES);const item=s[editIndex];item.title=editTitle.value;item.desc=editDesc.value;item.detailDesc=editDetailDesc.value;if(editMainImage.files[0])item.mainImage=await fileToData(editMainImage.files[0]);if(editDetailImages.files.length){const imgs=await Promise.all([...editDetailImages.files].map(fileToData));item.detailImages=[...(item.detailImages||[]),...imgs]}setData("renovaServices",s);editMainImage.value="";editDetailImages.value="";closeServiceEditor();loadServicesAdmin();refreshSite();alert("서비스 저장 완료")}
function saveSettings(){setData("renovaSettings",{phone1:phone1Input.value,phone2:phone2Input.value,blog:blogInput.value,kakao:kakaoInput.value});refreshSite();alert("저장 완료")}function loadSettingsAdmin(){const s=getData("renovaSettings",{phone1:"010-8476-7456",phone2:"010-9169-7557",blog:"",kakao:""});phone1Input.value=s.phone1;phone2Input.value=s.phone2;blogInput.value=s.blog;kakaoInput.value=s.kakao}
async function saveCase(){const title=caseTitle.value.trim(),desc=caseDesc.value.trim();if(!title){alert("제목을 입력하세요");return}const imgs=await Promise.all([...caseImages.files].slice(0,10).map(fileToData));const cases=getData("renovaCases",[]);cases.unshift({id:Date.now(),title,desc,images:imgs});setData("renovaCases",cases);caseTitle.value="";caseDesc.value="";caseImages.value="";renderCasesAdmin();refreshSite();alert("시공사례 저장 완료")}
function renderCasesAdmin(){const cases=getData("renovaCases",[]);caseList.innerHTML=cases.map(c=>`<div class="adminCard"><h3>${c.title}</h3><p>${c.desc||""}</p><div class="adminPreviewGrid">${(c.images||[]).map(img=>`<img src="${img}" onclick="openImage('${img}')">`).join("")}</div><button class="danger" onclick="deleteCase(${c.id})">삭제</button></div>`).join("")}
function deleteCase(id){setData("renovaCases",getData("renovaCases",[]).filter(x=>x.id!==id));renderCasesAdmin();refreshSite()}
refreshSite();